### ISSUE TITLE
catch error when number of attributes exceed number of categories

### ISSUE THREAD

**Issue by markheckmann** [markheckmann/gridsampler#12]
Warnung: Error in : The number of attributes 'a' must not exceed the number of categories, i.e. length of 'prob'
Stack trace (innermost first):
    71: sim_one_person [/Users/mark/Dropbox/_mh/programming/R/pkg_dev/grid/gridsampler/gridsampler/R/simulation.R#23]

**Comment by jemus42** [comment]
Not sure about the best way to tacke this, but here's an idea:

In an `observe` in `server.R`…
- Check if `length(input$minium1:input$maximum2`) > `input$maximum2`
- Add an `updateNumericInput` that decreases `input$maximum1` if previous check is `TRUE`

This should prevent the error from occurring, however I don't know how to tell the user that this is an error condition and he shouldn't do that.  
I could probably create a dummy input for a `conditionalPanel` to display a help/error message if that occurs, but there is probably a better way including javascript and alerts, both of which I'm embarrassingly unfamiliar with as of now.

**Comment by jemus42** [comment]
Would you be okay with a dependency on [shinyJS](https://github.com/daattali/shinyjs#usage-navbarpage)?

I've implemented the check as described above and it successfully prevents the offending configuration, but I'd like to inject an alert  / some kind of explanatory message.

Another thing I could do with shinyJS would be to disable the `maximum1` input element once the number of attributes is equal to the number of categories, which would also prevent the offending configuration and signal to the user that they are supposed stop. However, this probably would also benefit from an explanation.

As far as explanations for limiting the input go, maybe this could just be addressed in the tour and then I'm already done with it. ¯\_(ツ)_/¯

**Comment by markheckmann** [comment]
Yes. as shinyJS is on CRAN it's okay. Solution appears ok. Disabling the input would be nice. Lets test it :)

**Comment by jemus42** [comment]
Okay, I'm confused.

I implemented the `shinyJS` thing, but it doesn't disable the `numericInput` elements as it's supposed to. However, the bug doesn't appear anymore.  
[See demo video](http://dump.jemu.name/2016-08-15_1f7813o9tzlycbb.mp4)  

…What's going on there o.O

EDIT: I added a shinyjs branch with the current edits in case you want to try it out yourself

**Comment by jemus42** [comment]
Current method is not the prettiest but it's stable and works.
