### ISSUE TITLE
New probability presets for category panel.

### ISSUE THREAD

**Issue by markheckmann** [markheckmann/gridsampler#13]
Currently, we have a normal, Poisson, exponential and uniform preset. As category order does not matter, all presets can be dessending. So we could instead have (parameter in parenthesis):
- exponential (rate)
- uniform (none)
- linearly decreasing (none)
- quadratically decreasing with minimal value (factor, min)

**Comment by jemus42** [comment]
What should the linear decrease look like without a parameter?  
I could just use a uniform distribution and subtract a vector of the same length with increasing values, but that needs some delta value.

**Comment by markheckmann** [comment]
Good point. It also needs am minimal prob value. SO it linearily decreases from some value over the categories to meet the minimal given value in the last category.

**Comment by jemus42** [comment]
But that would mean it also needs a maximum probability value to start from, right? Or am I misunderstanding something?  

I'm thinking of linear functions which need a slope and a y intersection, so I can't wrap my head around how to do this with a single argument.

**Comment by markheckmann** [comment]
I think, there are no degrees fo freedom left here, as the probabilities sum up to one. 
When we have K=3 categories and the minimal probability (i.e. for last category) is, for example, P_k=.1, the other two values are not free no vary any more. However, I guess it's will be work to fiddle  out the formula.

**Comment by jemus42** [comment]
I was looking for an example for a linear probability density function and stumbled upon [this](http://stats.stackexchange.com/a/171631/80056) which, after some fiddleing, gave me this function:

```
dlin <- function(a = 0, len = 15) {
  s <- (1 + a * seq(0, 1 - 1/len, by = (1/len))) / 2
  s <- s/sum(s)
  return(s)
}
```

It produces `len` values which sum up to 1 and `a` is a parameter between `-1` (for negative slopes) and `+1` (for positive slopes, i.e. input could be limited to `[0, 1]`). 

I realize that's not what we talked about, but it seems to work and I'm undercoffeinated enough to be confused by linear equations right now, soooo… I'll just leave this here for now.

**Comment by markheckmann** [comment]
Here it is. You only need to make sure that p_k is capped at 1/k in the UI.

```
#' Linearily decreasing probabilities
#' 
#' @param k Number of values
#' @param p_k Probability of k-th (i.e. last) value (default 0).
#' 
p_linear <- function(k, p_k=0)
{
  slope <- (2 - 2*k*p_k) / (k*(1-k))
  intercept <- (p_k*(1+k)-2) / (1-k)
  intercept + 1:k*slope
}

K <- 5
plot(1:K, p_linear(K), type="h", ylim=c(0,.5))
plot(1:K, p_linear(K, .1), type="h", ylim=c(0,.5))
```
