### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by jemus42** [markheckmann/gridsampler#28]
CRAN availability would reduce the number of hoops potential users would have to jump through.  
Also, it would allow easy deployment to shinyapps.io, which (as far as my quick test just now) is not happy with a GitHub dependency and can't find `gridsampler`, presumably because it only checks CRAN.  

As of this moment, the package is pretty much good to go for submission to CRAN, as the `R CMD check` completes with 0 errors, warnings or notes. It would probably be only a matter of running `devtools::release()`

**Comment by markheckmann** [comment]
once all issue are gone, we are ready for CRAN

**Comment by jemus42** [comment]
I just checked the winbuilder (`devtools::build_win()`) and the results came back clear, so we're good to go on Windows, too!

**Comment by markheckmann** [comment]
nice!

2016-08-19 11:29 GMT+02:00 Lukas Burk notifications@github.com:

**Comment by jemus42** [comment]
Before we submit, I have to re-fix the vignette location, turns out I had it right the first time around, see https://twitter.com/JennyBryan/status/767792892257505280

I'll fix it when I'm home later today, I just wanted to make sure we don't submit with broken vignettes.

**Comment by jemus42** [comment]
Okay, fixed in 2c4b4a41aa5d7a6fa692ff6982a7096d0a136419, we're good to go, package-wise.

**Comment by markheckmann** [comment]
sent to CRAN
