### ISSUE TITLE
add tooltips for each button

### ISSUE THREAD

**Issue by markheckmann** [markheckmann/gridsampler#3]

**Comment by jemus42** [comment]
This should be possible using [shinyBS](https://ebailey78.github.io/shinyBS/docs/Tooltips_and_Popovers.html#addTooltip), however, I haven't used that yet, but I'll read through the docs.

**Comment by markheckmann** [comment]
This issue was from GTK times. Not sure if we still need tooltips, once we have a tour in place.

**Comment by jemus42** [comment]
Agree, tour should be sufficient. Cleaning up.
