### ISSUE TITLE
Update gh-pages branch with new vignette

### ISSUE THREAD

**Issue by jemus42** [markheckmann/gridsampler#31]
Alternatively, use the new GitHub feature to build the github pages site directly from a `docs` dir.  
Steps needed:
- [X] Copy vignette (named `index.html`) to `docs` dir
- [x] Rebuild github pages from repo settings, choose this location

**Comment by markheckmann** [comment]
where do I find a manual for this feature?

**Comment by jemus42** [comment]
It's documented [here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)

**Comment by markheckmann** [comment]
done
