### ISSUE TITLE
Use travis-ci with this repo?

### ISSUE THREAD

**Issue by jemus42** [markheckmann/gridsampler#32]
It would be very simple to set up travis, you'd only need to [log in to travis](https://travis-ci.org/), enable this repo and add a simple `.travis.yml` to this repo's basedir.

The following would suffice:

``` yaml
language: r
sudo: false
cache: packages
```

The benefit would be automated builds and tests, the results of which could also be communicated to users via a badge in the repo's README, as is very common for R packages on GitHub ([See my other package](https://github.com/tadaadata/tadaatoolbox#tadaatoolbox)).

**Comment by markheckmann** [comment]
closed in commit 769485aa34762ea1d489d2cd210effdd30f6afa5
