### ISSUE TITLE
use R expressions in fields fails

### ISSUE THREAD

**Issue by markheckmann** [markheckmann/gridsampler#35]
Using an R expression as, for example, `seq(10,80, by=10)`appears not to work correctly. It odes not throw an error, but the values are not shown in the simulation graphics, i.e. not used for the analysis.

![image](https://cloud.githubusercontent.com/assets/152927/18044492/78c8cffc-6dce-11e6-99ba-d89624716df7.png)

**Comment by markheckmann** [comment]
This works

![image](https://cloud.githubusercontent.com/assets/152927/18047560/d2f9ed12-6ddd-11e6-85f0-4104c8cb8134.png)

This causes crash

![image](https://cloud.githubusercontent.com/assets/152927/18047593/f980507a-6ddd-11e6-91c6-7e99c87485e7.png)

Maybe using a tryCatch evaluation of the entered text wrapped in `c`, i.e. `paste0("c(", text, ")")` and check if it is a numeric vector. Else alert user.

**Comment by jemus42** [comment]
Well, that's a tricky one. Need to figure that one out later.

**Comment by markheckmann** [comment]
Try integrating something like this:

```
string_contains_numeric_vector <- function(s)
{
  # wrap in c to get numeric vector for vectors 
  # seperated by comma e.g. 1:3, 3:4
  s <- paste0("c(", s, ")")   

  # can string be evaluated without failing?
  v <- tryCatch(
    eval(parse(text=s)),
    error = function(e) simpleError("no valid R expression")
  )

  # evaluates to numeric vector?
  list(check= is.numeric(v) & is.vector(v),
       vector = v)
}

string_contains_numeric_vector("1:3")
string_contains_numeric_vector("seq(1,3)")
string_contains_numeric_vector("seq(1,3), seq(1,3)")  # is okay

string_contains_numeric_vector("a, 1,2")          # fails: no valid R
string_contains_numeric_vector("'a', 1,2")        # fails: valid R but not numeric
string_contains_numeric_vector("arbitary stuff")  # fails: no valid R
```

**Comment by jemus42** [comment]
Closing this for now.
