### ISSUE TITLE
making all fields robust against error wrong parameters

### ISSUE THREAD

**Issue by markheckmann** [markheckmann/gridsampler#36]
**The following will cause the app to crash:**
- [x] entering negative values in almost any of the fields.
- [x] entering negative values for (N) or (R) in upper part of panel 3 leads to crash
  ![image](https://cloud.githubusercontent.com/assets/152927/18044957/90fa724a-6dd0-11e6-8c3d-9045be02cc6f.png)

**The following will NOT cause the app to crash but lead to non sensible results:**
- [x] entering negative values for (M) or (C) does not lead to crash but displays non sensible graph.
  ![image](https://cloud.githubusercontent.com/assets/152927/18045037/10e5656e-6dd1-11e6-85a3-6cc1c37a38e6.png)

The lists are probably incomplete.

**Comment by jemus42** [comment]
I fixed the crashes, but since the input is invalid I don't really know how to treat it.  

Current approaches are either "use the absolute value" or "…just roll with it and don't crash"
