### ISSUE TITLE
Shiny now supports bookmarkable states

### ISSUE THREAD

**Issue by jemus42** [markheckmann/gridsampler#37]
…Should we implement that?  
Actually including the functionality seems trivial, the only real question would be where to put the bookmark button.

See: http://shiny.rstudio.com/articles/bookmarking-state.html

**Comment by markheckmann** [comment]
Okay, lets open a new branch and give it a try. It will be a real benefit if it works. Also, it will be interesting to see if we can make the bookmarks work in our case, where there are many values which are stored as reactive values.

**Comment by markheckmann** [comment]
After reconsidering, this is not really needed.
