### ISSUE TITLE
Cosmetic changes

### ISSUE THREAD

**Issue by markheckmann** [markheckmann/gridsampler#7]
- round probabilities in panel 2 to 3 instead of four digits and remove leading zero, i.e. .123 instead of 0.123 to save space
  ![image](https://cloud.githubusercontent.com/assets/152927/17648599/ea97699a-621b-11e6-89db-e5f0c44b1bd4.png)
- round probabilities in both input fields to 3 digits
  ![image](https://cloud.githubusercontent.com/assets/152927/17648601/03478e20-621c-11e6-930f-c02c7873d171.png)

**Comment by jemus42** [comment]
I could also rotate the numbers by 90°, which would save the most space but slightly impact readability.

**Comment by jemus42** [comment]
As for the probabilities in the input elements, I can't just round them because that would mean to actually change the values used for computations, and I'm not sure how many decimals are required for solid simulations.

**Comment by jemus42** [comment]
Conclusion: 3 decimals is enough

**Comment by jemus42** [comment]
Fixed with [commit 7290581](https://github.com/markheckmann/gridsampler/commit/72905818964a7a5f5a6776536993610c32f16497)
